### ISSUE TITLE
some bug

### ISSUE THREAD

**Issue by SeliliPona** [Stereowalker/Controller-Support-Mod#3]
So I guess I got a controller working. I tried rebinding something and I crashed with this report:
---- Minecraft Crash Report ----
// On the bright side, I bought you a teddy bear!

Time: 4/21/20 9:13 AM
Description: Ticking screen

java.lang.NullPointerException: Ticking screen
	at com.stereowalker.controllermod.client.controller.ControllerHelper.listenForButton(ControllerHelper.java:124) ~[?:1.3.0] {re:classloading,pl:runtimedistcleaner:A}
	at com.stereowalker.controllermod.client.gui.screen.ControllerInputOptionsScreen.tick(ControllerInputOptionsScreen.java:165) ~[?:1.3.0] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.lambda$runTick$19(Minecraft.java:1366) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.gui.screen.Screen.wrapScreenError(Screen.java:446) ~[?:?] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1365) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.func_195542_b(Minecraft.java:905) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:554) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.main.Main.main(SourceFile:204) ~[1.15.2-forge-31.1.0.jar:?] {re:classloading}
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_74] {}
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_74] {}
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_74] {}
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_74] {}
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider.lambda$launchService$0(FMLClientLaunchProvider.java:56) ~[forge-1.15.2-31.1.0.jar:31.1] {}
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37) [modlauncher-5.0.0-milestone.4.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:54) [modlauncher-5.0.0-milestone.4.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72) [modlauncher-5.0.0-milestone.4.jar:?] {}
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:81) [modlauncher-5.0.0-milestone.4.jar:?] {}
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:65) [modlauncher-5.0.0-milestone.4.jar:?] {}

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at com.stereowalker.controllermod.client.controller.ControllerHelper.listenForButton(ControllerHelper.java:124)
	at com.stereowalker.controllermod.client.gui.screen.ControllerInputOptionsScreen.tick(ControllerInputOptionsScreen.java:165)
	at net.minecraft.client.Minecraft.lambda$runTick$19(Minecraft.java:1366)

-- Affected screen --
Details:
	Screen name: com.stereowalker.controllermod.client.gui.screen.ControllerInputOptionsScreen
Stacktrace:
	at net.minecraft.client.gui.screen.Screen.wrapScreenError(Screen.java:446)
	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1365)
	at net.minecraft.client.Minecraft.func_195542_b(Minecraft.java:905)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:554)
	at net.minecraft.client.main.Main.main(SourceFile:204)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider.lambda$launchService$0(FMLClientLaunchProvider.java:56)
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37)
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:54)
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72)
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:81)
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:65)

-- System Details --
Details:
	Minecraft Version: 1.15.2
	Minecraft Version ID: 1.15.2
	Operating System: Mac OS X (x86_64) version 10.11.6
	Java Version: 1.8.0_74, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 1615948896 bytes (1541 MB) / 2147483648 bytes (2048 MB) up to 2147483648 bytes (2048 MB)
	CPUs: 2
	JVM Flags: 8 total; -Xss1M -Xmx2G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	ModLauncher: 5.0.0-milestone.4+67+b1a340b
	ModLauncher launch target: fmlclient
	ModLauncher naming: srg
	ModLauncher services: 
		/eventbus-2.0.0-milestone.1-service.jar eventbus PLUGINSERVICE 
		/forge-1.15.2-31.1.0.jar object_holder_definalize PLUGINSERVICE 
		/forge-1.15.2-31.1.0.jar runtime_enum_extender PLUGINSERVICE 
		/accesstransformers-2.0.0-milestone.1-shadowed.jar accesstransformer PLUGINSERVICE 
		/forge-1.15.2-31.1.0.jar capability_inject_definalize PLUGINSERVICE 
		/forge-1.15.2-31.1.0.jar runtimedistcleaner PLUGINSERVICE 
		/forge-1.15.2-31.1.0.jar fml TRANSFORMATIONSERVICE 
	FML: 31.1
	Forge: net.minecraftforge:31.1.0
	FML Language Providers: 
		javafml@31.1
		minecraft@1
	Mod List: 
		forge-1.15.2-31.1.0-client.jar Minecraft {minecraft@1.15.2 DONE}
		forge-1.15.2-31.1.0-universal.jar Forge {forge@31.1.0 DONE}
		ControllerSupport-1.15.2-1.3.0.jar Controller Support {controllermod@1.3.0 DONE}
	Launched Version: 1.15.2-forge-31.1.0
	Backend library: LWJGL version 3.2.1 build 12
	Backend API: ATI Radeon HD 2600 PRO OpenGL Engine GL version 2.1 ATI-10.0.52, ATI Technologies Inc.
	GL Caps: Using framebuffer using ARB_framebuffer_object extension
	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'forge'
	Type: Client (map_client.txt)
	Resource Packs: vanilla
	Current Language: English (US)
	CPU: 2x Intel(R) Core(TM)2 Duo CPU T7700 @ 2.40GHz

**Comment by Stereowalker** [comment]
I believe I've fixed this already, so I'm closing this
